"""retinanalysis — lazy top-level package.

Public names (functions, classes, submodules, path constants) are resolved
on first access via PEP 562 ``__getattr__`` instead of being imported all at
once. This keeps ``import retinanalysis`` fast (~0.1 s instead of ~3.5 s) so
Jupyter kernel restarts feel instant: DataJoint, matplotlib, scipy and xarray
are pulled in only when you actually call something that needs them.

Behaviour is identical to the old eager import:

* ``import retinanalysis as ra; ra.analyze_experiment(...)`` works the same.
* ``from retinanalysis import DATA_DIR`` works (resolved via ``__getattr__``).
* Every name the old eager ``__init__`` exposed is still resolvable. Names
  that only ever existed because an old ``from .x import *`` leaked them
  (typing aliases, ``np``/``pd``, the unused schema-table placeholders, ...)
  are recovered by ``_STAR_MODULES`` fallback below.

The two registries are generated by introspecting the eager package; see
``tests/test_lazy_import.py`` which asserts name-for-name parity and that the
common offline workflow does not import DataJoint.

NOTE on DataJoint: the old ``config.schema`` was imported first and opened the
DB connection at ``import`` time. Now ``schema`` (and the connection) load on
first access to anything DataJoint-backed. Every consumer of the schema tables
imports ``retinanalysis.config.schema`` directly, so the tables are always
declared before use — the old "must be first" ordering is preserved naturally.
"""
from __future__ import annotations

import importlib

# name -> dotted module path, for attributes whose value *is* a module.
_SUBMODULES = {
    'DJ_GUI': 'retinanalysis.DJ_GUI',
    'SCutils': 'retinanalysis.SCutils',
    'sc_explore': 'retinanalysis.SCutils.explore',
    '_cell_match_mod': 'retinanalysis.utils.cell_match',
    '_dedup_mod': 'retinanalysis.utils.dedup',
    '_local_cache_mod': 'retinanalysis.utils.local_cache',
    '_offline_store_mod': 'retinanalysis.utils.offline_store',
    '_protocol_qc_mod': 'retinanalysis.utils.protocol_qc',
    '_psth_mod': 'retinanalysis.utils.psth',
    'igor_export': 'retinanalysis.utils.igor_export',
    '_raster_mod': 'retinanalysis.utils.raster',
    '_regen_pkg': 'retinanalysis.utils.regen',
    '_sorting_qc_mod': 'retinanalysis.utils.sorting_qc',
    '_visual_qc_mod': 'retinanalysis.utils.visual_qc',
    'analysis_chunk': 'retinanalysis.classes.analysis_chunk',
    'analyze': 'retinanalysis.analyze',
    'cell_type_check': 'retinanalysis.utils.cell_type_check',
    'cell_type_utils': 'retinanalysis.utils.cell_type_utils',
    'classes': 'retinanalysis.classes',
    'config': 'retinanalysis.config',
    'cv2': 'cv2',
    'database_pop': 'retinanalysis.utils.database_pop',
    'database_utils': 'retinanalysis.utils.database_utils',
    'datajoint_utils': 'retinanalysis.utils.datajoint_utils',
    'datetime': 'datetime',
    'dedup': 'retinanalysis.classes.dedup',
    'dj': 'datajoint',
    'ei_utils': 'retinanalysis.utils.ei_utils',
    'h5py': 'h5py',
    'json': 'json',
    'mea_pipeline': 'retinanalysis.classes.mea_pipeline',
    'mosaic_overlay': 'retinanalysis.utils.mosaic_overlay',
    'np': 'numpy',
    'os': 'os',
    'pd': 'pandas',
    'plt': 'matplotlib.pyplot',
    'protocols': 'retinanalysis.protocols',
    'qc': 'retinanalysis.classes.qc',
    'regen': 'retinanalysis.regen',
    'response': 'retinanalysis.classes.response',
    'sc_pipeline': 'retinanalysis.classes.sc_pipeline',
    'schema': 'retinanalysis.config.schema',
    'settings': 'retinanalysis.config.settings',
    'stim': 'retinanalysis.classes.stim',
    'tqdm': 'tqdm',
    'utils': 'retinanalysis.utils',
    'vision_utils': 'retinanalysis.utils.vision_utils',
    'xr': 'xarray',
}

# name -> dotted module path, for functions / classes / path constants.
_ATTR_TO_MODULE = {
    'ANALYSIS_DIR': 'retinanalysis.config.settings',
    'AnalysisChunk': 'retinanalysis.classes.analysis_chunk',
    'DATA_DIR': 'retinanalysis.config.settings',
    'D_REGEN_FXNS': 'retinanalysis.classes.stim',
    'DedupBlock': 'retinanalysis.classes.dedup',
    'H5_DIR': 'retinanalysis.config.settings',
    'LOCAL_CACHE_ROOT': 'retinanalysis.utils.local_cache',
    'MEAPipeline': 'retinanalysis.classes.mea_pipeline',
    'MEAQC': 'retinanalysis.classes.qc',
    'MEAResponseBlock': 'retinanalysis.classes.response',
    'MEAResponseGroup': 'retinanalysis.classes.response',
    'MEAStimBlock': 'retinanalysis.classes.stim',
    'MEAStimGroup': 'retinanalysis.classes.stim',
    'META_DIR': 'retinanalysis.config.settings',
    'OUTPUT_DIR': 'retinanalysis.config.settings',
    'OfflineDataset': 'retinanalysis.utils.offline_store',
    'PROTOCOL_REPOS_ROOT': 'retinanalysis.config.settings',
    'PURGE_CONFIRM_TOKEN': 'retinanalysis.utils.database_utils',
    'QCThresholds': 'retinanalysis.utils.protocol_qc',
    'QUERY_DIR': 'retinanalysis.config.settings',
    'RAW_DIR': 'retinanalysis.config.settings',
    'RawTraces': 'retinanalysis.classes.raw',
    'ResponseBlock': 'retinanalysis.classes.response',
    'SCResponseBlock': 'retinanalysis.classes.response',
    'SS_VERSION_PRIORITY': 'retinanalysis.analyze',
    'StimBlock': 'retinanalysis.classes.stim',
    'TAGS_DIR': 'retinanalysis.config.settings',
    'USER': 'retinanalysis.config.settings',
    'add_parameters_col': 'retinanalysis.utils.datajoint_utils',
    'add_ss_version_column': 'retinanalysis.analyze',
    'analyze_experiment': 'retinanalysis.analyze',
    'analyze_experiments': 'retinanalysis.analyze',
    'apply_publication_style': 'retinanalysis.utils.style',
    'append_animal': 'retinanalysis.utils.database_pop',
    'append_cell': 'retinanalysis.utils.database_pop',
    'append_celltypefiles': 'retinanalysis.utils.database_pop',
    'append_data': 'retinanalysis.utils.database_pop',
    'append_epoch': 'retinanalysis.utils.database_pop',
    'append_epoch_block': 'retinanalysis.utils.database_pop',
    'append_epoch_group': 'retinanalysis.utils.database_pop',
    'append_experiment': 'retinanalysis.utils.database_pop',
    'append_experiment_analysis': 'retinanalysis.utils.database_pop',
    'append_preparation': 'retinanalysis.utils.database_pop',
    'append_protocol': 'retinanalysis.utils.database_pop',
    'append_response': 'retinanalysis.utils.database_pop',
    'append_sorting_chunk': 'retinanalysis.utils.database_pop',
    'append_sorting_files': 'retinanalysis.utils.database_pop',
    'append_stimulus': 'retinanalysis.utils.database_pop',
    'append_tags': 'retinanalysis.utils.database_pop',
    'apply_dedup': 'retinanalysis.utils.dedup',
    'available_protocols': 'retinanalysis.regen',
    'bandwidth_scope': 'retinanalysis.utils.bandwidth',
    'browse_cells_qc': 'retinanalysis.utils.visual_qc',
    'browse_chunk_summaries': 'retinanalysis.utils.chunk_summary',
    'browse_epoch_count_heatmaps': 'retinanalysis.utils.raster',
    'browse_epoch_rasters': 'retinanalysis.utils.raster',
    'browse_experiment_tree': 'retinanalysis.utils.db_summary',
    'build_cell_match_table': 'retinanalysis.utils.cell_match',
    'build_tuple': 'retinanalysis.utils.database_pop',
    'cell_match_csv_path': 'retinanalysis.utils.cell_match',
    'cell_activity_in_window': 'retinanalysis.utils.mosaic_overlay',
    'cell_type_summary': 'retinanalysis.utils.chunk_summary',
    'cells_inside_array': 'retinanalysis.utils.mosaic_overlay',
    'cells_sharing_electrode': 'retinanalysis.classes.raw',
    'check_frame_times': 'retinanalysis.classes.response',
    'check_psth_timing': 'retinanalysis.utils.psth',
    'child_table': 'retinanalysis.utils.database_pop',
    'classification_transfer': 'retinanalysis.utils.vision_utils',
    'clear_local_cache': 'retinanalysis.utils.local_cache',
    'cluster_match': 'retinanalysis.utils.vision_utils',
    'compare_cache_vs_source': 'retinanalysis.utils.local_cache',
    'compute_ei_stats': 'retinanalysis.utils.cell_match',
    'compute_image_onset_offset_frames': 'retinanalysis.utils.regen',
    'create_dictionary_from_file': 'retinanalysis.utils.vision_utils',
    'color_for_celltype': 'retinanalysis.utils.style',
    'colors_for_celltypes': 'retinanalysis.utils.style',
    'colors_for_conditions': 'retinanalysis.utils.style',
    'diverging_cmap': 'retinanalysis.utils.style',
    'create_mea_pipeline': 'retinanalysis.classes.mea_pipeline',
    'create_mea_pipeline_cached': 'retinanalysis.utils.local_cache',
    'create_mea_response_group': 'retinanalysis.classes.response',
    'create_mea_stim_group': 'retinanalysis.classes.stim',
    'dedup_pipeline': 'retinanalysis.utils.dedup',
    'delete_experiments': 'retinanalysis.utils.database_utils',
    'detect_ss_version': 'retinanalysis.analyze',
    'djconnect': 'retinanalysis.utils.datajoint_utils',
    'ei_corr': 'retinanalysis.utils.vision_utils',
    'electrode_geometry': 'retinanalysis.utils.mosaic_overlay',
    'electrode_positions_canvas_px': 'retinanalysis.utils.mosaic_overlay',
    'block_qc_metrics': 'retinanalysis.utils.protocol_qc',
    'cell_qc_metrics': 'retinanalysis.utils.protocol_qc',
    'epoch_condition_table': 'retinanalysis.utils.protocol_qc',
    'epoch_population_counts': 'retinanalysis.utils.protocol_qc',
    'filter_cells_by_qc': 'retinanalysis.utils.protocol_qc',
    'suggest_epoch_range': 'retinanalysis.utils.protocol_qc',
    'plot_epoch_range': 'retinanalysis.utils.protocol_qc',
    'plot_qc_mosaic': 'retinanalysis.utils.protocol_qc',
    'plot_mosaic_activity': 'retinanalysis.utils.mosaic_overlay',
    'grating_frame': 'retinanalysis.regen.variable_mean_drifting_grating',
    'grating_geometry': 'retinanalysis.regen.variable_mean_drifting_grating',
    'um_to_pixels': 'retinanalysis.utils.stimulus_frame',
    'canvas_offsets': 'retinanalysis.utils.stimulus_frame',
    'project_on_axis': 'retinanalysis.utils.stimulus_frame',
    'grating_luminance': 'retinanalysis.utils.stimulus_frame',
    'apply_circular_aperture': 'retinanalysis.utils.stimulus_frame',
    'sample_cells_by_type': 'retinanalysis.utils.sorting_qc',
    'parse_protocol_source': 'retinanalysis.utils.protocol_source',
    'protocol_source_path': 'retinanalysis.utils.protocol_source',
    'block_parameters': 'retinanalysis.utils.protocol_source',
    'condition_keys': 'retinanalysis.utils.protocol_source',
    'epoch_count_matrix': 'retinanalysis.utils.raster',
    'epoch_spikes_to_psth': 'retinanalysis.utils.psth',
    'experiment_tree': 'retinanalysis.utils.db_summary',
    'fill_tables': 'retinanalysis.utils.database_pop',
    'filter_available_types': 'retinanalysis.utils.cell_type_utils',
    'find_available_datasets': 'retinanalysis.analyze',
    'find_duplicate_groups': 'retinanalysis.utils.dedup',
    'firing_rates_by_type': 'retinanalysis.utils.chunk_summary',
    'find_path': 'retinanalysis.config.settings',
    'find_protocol_repo': 'retinanalysis.config.settings',
    'find_raw_path': 'retinanalysis.config.settings',
    'find_varying_epoch_parameters': 'retinanalysis.utils.datajoint_utils',
    'gaussian_filter_1d': 'retinanalysis.utils.psth',
    'gen_meta_list': 'retinanalysis.utils.database_pop',
    'gen_tags': 'retinanalysis.utils.database_pop',
    'get_analysis_vcd': 'retinanalysis.utils.vision_utils',
    'get_block_chunk': 'retinanalysis.utils.database_pop',
    'get_block_id_from_datafile': 'retinanalysis.utils.datajoint_utils',
    'get_classification_file_path': 'retinanalysis.utils.vision_utils',
    'get_datasets_from_protocol_names': 'retinanalysis.utils.datajoint_utils',
    'get_df_dict_vals': 'retinanalysis.utils.regen',
    'get_display_params_by_exp': 'retinanalysis.utils.datajoint_utils',
    'get_ei_and_map': 'retinanalysis.utils.ei_utils',
    'get_ells': 'retinanalysis.utils.vision_utils',
    'get_epoch_data_from_exp': 'retinanalysis.utils.datajoint_utils',
    'get_epochblock_amp_data': 'retinanalysis.utils.datajoint_utils',
    'get_epochblock_frame_data': 'retinanalysis.utils.datajoint_utils',
    'get_epochblock_query': 'retinanalysis.utils.datajoint_utils',
    'get_epochblock_response_query': 'retinanalysis.utils.datajoint_utils',
    'get_epochblock_timing': 'retinanalysis.utils.datajoint_utils',
    'get_exp_summary': 'retinanalysis.utils.datajoint_utils',
    'get_h5_file': 'retinanalysis.utils.datajoint_utils',
    'get_image_paths_across_epochs': 'retinanalysis.utils.regen',
    'get_n_cells_of_interest': 'retinanalysis.utils.datajoint_utils',
    'get_noise_chunks_sorted_by_distance': 'retinanalysis.utils.datajoint_utils',
    'get_noise_name_by_exp': 'retinanalysis.utils.datajoint_utils',
    'get_old_presentimages_transitions': 'retinanalysis.utils.regen',
    'get_present_images_transitions': 'retinanalysis.utils.regen',
    'get_presentation_times': 'retinanalysis.utils.vision_utils',
    'get_protocol_from_datafile': 'retinanalysis.utils.vision_utils',
    'get_protocol_vcd': 'retinanalysis.utils.vision_utils',
    'get_roi_dict': 'retinanalysis.utils.vision_utils',
    'get_spatial_noise_frames': 'retinanalysis.utils.regen',
    'get_spike_dict': 'retinanalysis.utils.vision_utils',
    'get_spike_xarr': 'retinanalysis.utils.vision_utils',
    'get_stage_frame_rate_by_exp': 'retinanalysis.utils.datajoint_utils',
    'get_timecourses': 'retinanalysis.utils.vision_utils',
    'get_top_electrodes': 'retinanalysis.utils.ei_utils',
    'get_typing_files_for_datasets': 'retinanalysis.utils.datajoint_utils',
    'ingest_source_dirs': 'retinanalysis.config.settings',
    'lcr_video_device_um_to_pix': 'retinanalysis.utils.regen',
    'load_all_present_images': 'retinanalysis.utils.regen',
    'load_and_process_img': 'retinanalysis.utils.regen',
    'load_cached_pipeline': 'retinanalysis.utils.local_cache',
    'load_canonical_cell_types': 'retinanalysis.utils.cell_type_utils',
    'load_cell_match': 'retinanalysis.utils.cell_match',
    'load_doves_img': 'retinanalysis.utils.regen',
    'load_mp4': 'retinanalysis.utils.regen',
    'load_offline_data': 'retinanalysis.utils.offline_store',
    'load_offline_many': 'retinanalysis.utils.offline_store',
    'load_or_build_offline': 'retinanalysis.utils.offline_store',
    'load_or_compute_protocol_qc': 'retinanalysis.utils.protocol_qc',
    'load_protocol_qc': 'retinanalysis.utils.protocol_qc',
    'load_visual_qc': 'retinanalysis.utils.visual_qc',
    'list_database_experiments': 'retinanalysis.utils.database_utils',
    'list_experiment_dates': 'retinanalysis.utils.db_summary',
    'local_cache_status': 'retinanalysis.utils.local_cache',
    'make_all_doves_movies': 'retinanalysis.utils.regen',
    'make_checkerboard_noise_project': 'retinanalysis.utils.regen',
    'make_doves_perturbation_alpha': 'retinanalysis.utils.regen',
    'make_expanding_spots': 'retinanalysis.utils.regen',
    'make_single_doves_movie': 'retinanalysis.utils.regen',
    'make_spatial_noise': 'retinanalysis.utils.regen',
    'make_spot_image': 'retinanalysis.utils.regen',
    'make_table_dict': 'retinanalysis.utils.database_pop',
    'map_cell_type': 'retinanalysis.utils.cell_type_utils',
    'match_diagnostics': 'retinanalysis.utils.cell_match',
    'mea_protocol_counts': 'retinanalysis.utils.db_summary',
    'max_id': 'retinanalysis.utils.database_pop',
    'mirror_to_local_cache': 'retinanalysis.utils.local_cache',
    'network_bandwidth_gauge_widget': 'retinanalysis.utils.bandwidth',
    'network_bytes_resolved': 'retinanalysis.config.settings',
    'network_resolutions_count': 'retinanalysis.config.settings',
    'offline_h5_path': 'retinanalysis.utils.offline_store',
    'parent_table': 'retinanalysis.utils.database_pop',
    'parse_data': 'retinanalysis.utils.database_pop',
    'pick_typing_file': 'retinanalysis.analyze',
    'pipeline_cache_path': 'retinanalysis.utils.local_cache',
    'plot_cell_type_check': 'retinanalysis.utils.cell_type_check',
    'plot_cell_type_grid': 'retinanalysis.utils.cell_type_check',
    'plot_chunk_panels': 'retinanalysis.utils.chunk_summary',
    'plot_ei_map': 'retinanalysis.utils.ei_utils',
    'figure_to_png': 'retinanalysis.utils.browse',
    'png_browser': 'retinanalysis.utils.browse',
    'plot_epoch_count_heatmap': 'retinanalysis.utils.raster',
    'plot_epoch_rasters': 'retinanalysis.utils.raster',
    'plot_epoch_spike_counts': 'retinanalysis.utils.raster',
    'plot_mosaics_for_all_datasets': 'retinanalysis.utils.datajoint_utils',
    'plot_firing_rate_distribution': 'retinanalysis.utils.chunk_summary',
    'plot_match_qc': 'retinanalysis.utils.cell_match',
    'plot_mosaics_for_datasets': 'retinanalysis.utils.datajoint_utils',
    'plot_raster_with_psth': 'retinanalysis.utils.raster',
    'plot_sorting_qc': 'retinanalysis.classes.raw',
    'plot_sorting_qc_grid': 'retinanalysis.classes.raw',
    'plot_spike_count_distribution': 'retinanalysis.utils.chunk_summary',
    'plot_stim_with_mosaic': 'retinanalysis.utils.mosaic_overlay',
    'plot_sts_over_trace': 'retinanalysis.classes.raw',
    'populate_database': 'retinanalysis.utils.database_utils',
    'populate_ndf_column': 'retinanalysis.utils.datajoint_utils',
    'primary_electrode_of_cell': 'retinanalysis.classes.raw',
    'print_network_gauge': 'retinanalysis.utils.bandwidth',
    'protocol_qc_csv_path': 'retinanalysis.utils.protocol_qc',
    'psth_time_axis': 'retinanalysis.utils.psth',
    'purge_database': 'retinanalysis.utils.database_utils',
    'purge_experiments': 'retinanalysis.utils.database_utils',
    'recording_counts': 'retinanalysis.utils.db_summary',
    'recording_summary': 'retinanalysis.utils.db_summary',
    'regen_stimulus': 'retinanalysis.regen',
    'reload_celltypefiles': 'retinanalysis.utils.database_pop',
    'reload_experiment_data': 'retinanalysis.utils.database_utils',
    'render_displayed_canvas': 'retinanalysis.regen',
    'reset_network_gauge': 'retinanalysis.config.settings',
    'reshape_ei': 'retinanalysis.utils.ei_utils',
    'resolve_noise_chunk': 'retinanalysis.analyze',
    'resolve_protocol_subdir': 'retinanalysis.utils.protocol_qc',
    'sample_and_plot_sorting_qc': 'retinanalysis.utils.sorting_qc',
    'sample_sorting_qc_cells': 'retinanalysis.utils.sorting_qc',
    'save_cell_match': 'retinanalysis.utils.cell_match',
    'save_offline_data': 'retinanalysis.utils.offline_store',
    'save_protocol_qc': 'retinanalysis.utils.protocol_qc',
    'scroll_table': 'retinanalysis.SCutils.explore',
    'search_protocol': 'retinanalysis.utils.datajoint_utils',
    'select_good_cells': 'retinanalysis.utils.visual_qc',
    'short_protocol': 'retinanalysis.utils.db_summary',
    'sort_electrode_map': 'retinanalysis.utils.ei_utils',
    'species_counts': 'retinanalysis.utils.db_summary',
    'sorting_qc_gui': 'retinanalysis.utils.sorting_qc',
    'spike_counts_by_type': 'retinanalysis.utils.chunk_summary',
    'spike_times_to_psth': 'retinanalysis.utils.psth',
    'summarize_batch_results': 'retinanalysis.analyze',
    'tier_dirs': 'retinanalysis.config.settings',
    'visual_qc_csv_path': 'retinanalysis.utils.visual_qc',
}

# Modules whose old ``from .x import *`` populated this namespace. Replayed on
# a lookup miss so any incidental name those star-imports leaked (typing
# aliases, ``np``/``pd``/``display``, ``gaussian_filter``, the unused
# schema-table placeholders, ...) still resolves. Real workflows never hit
# this path; the documented API is all in the two registries above.
_STAR_MODULES = (
    'retinanalysis.utils.database_pop',
    'retinanalysis.utils.database_utils',
    'retinanalysis.utils.datajoint_utils',
    'retinanalysis.utils.ei_utils',
    'retinanalysis.utils.regen',
    'retinanalysis.utils.vision_utils',
)


def __getattr__(name):
    """Import the module that provides ``name`` on first access (PEP 562)."""
    target = _SUBMODULES.get(name)
    if target is not None:
        module = importlib.import_module(target)
        globals()[name] = module
        return module

    target = _ATTR_TO_MODULE.get(name)
    if target is not None:
        value = getattr(importlib.import_module(target), name)
        globals()[name] = value
        return value

    for modpath in _STAR_MODULES:
        module = importlib.import_module(modpath)
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals()) | set(_SUBMODULES) | set(_ATTR_TO_MODULE))


__all__ = sorted(
    {n for n in (*_SUBMODULES, *_ATTR_TO_MODULE) if not n.startswith('_')}
)
